### ISSUE TITLE
Installing error in windows

### ISSUE THREAD

**Issue by mills32** [bbbbbr/gimp-tilemap-gb#1]
Hi. 
I talk to you at gbdev forums I was going to test the plugin but I could not install it.
It shows an error about not finding libcairo-2.dll (the file is there).
I had to replace that file, and even then the plugin refused to work, a lot of missing dll's and stuff.

Thanks.

**Comment by bbbbbr** [comment]
Is it Windows? If so, what OS version and which version of Gimp (version + x32/x64)? 

I've only tested the Windows build in a Win 10 VM with Gimp 2.10 (I think 2.10, but can't boot that VM at the moment to verify).

Just to check- which folder did you copy the plugin to?

I built against Gimp 2.8 x32 hoping that would make it more compatible all-around. But perhaps it'll be more complicated than that.

**Comment by mills32** [comment]
Hi. I'm using windows 8, 32 bit and Gimp 2.10.
Also the folder seems to be the same in all gimp installs: C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins

It's better to use python scripts I think. But I don't know if in this case is possible.

Maybe if I compile the plugin myself... But right now I can't compile c for pc :(.

Thanks.

EDIT:

I installed Gimp 2.10.12, and it worked :).

**Comment by bbbbbr** [comment]
Thanks & glad it worked! 

I'll update the Readme with that requirement.

I now see the build VM pulled a 2.10 master instead of a 2.8 branch for the Windows build.
