### ISSUE TITLE
install plugin to gimp (ubuntu) SOLVED

### ISSUE THREAD

**Issue by jackygoule** [bbbbbr/gimp-tilemap-gb#7]
Hello i download the linux plugin and put it on the folder ./gimp/2.10/plugins
But i don't find him.

**Comment by bbbbbr** [comment]
Can you be more specific?

* Which file are you putting there? (should be: download `gimp-file-tilemap-linux.zip`, unzip the file and put the resulting `file-tilemap` into your plugins folder)
* How are you determining that it doesn't find the plugin?
* Which version of GIMP do you have?

If it's working, you should see the option to open/save/export "GBR ..." and "GBM ..." files in the detailed file type lists of the GIMP dialogs.

**Comment by jackygoule** [comment]
Thanks for your answer i do a error.I put the executable  console file and not the file plugin.
So the plugin seem to work.
my version of GIMP:GIMP 2.10.18
Sorry for my mistake ,i have other problem but is not the same issue 
Thanks for your help
