### ISSUE TITLE
instal in gimp

### ISSUE THREAD

**Issue by retroarch-girl** [bbbbbr/gimp-tilemap-gb#9]
Hi

As a complete beginner in gimp: how to install it in windows?

**Comment by bbbbbr** [comment]
Download the latest version from the "Releases" area, then copy the "file-tilemap" to your GIMP plugin folder.

On  Windows, that may be: C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins

Then re-start GIMP

**Comment by retroarch-girl** [comment]
Where will this appear in GIMP of where to open the game boy map builder? I don't find it in any menu in GIMP

https://raw.githubusercontent.com/bbbbbr/gimp-tilemap/master/info/gimp-tilemap-plugin-screenshot.png

Not sure if it's installed correctly. I have copied it directly into that folder (without making subfolder)

**Comment by bbbbbr** [comment]
It is an import/export file type plugin, so it will not show up in the main menus. Just in the list of supported file types when opening or exporting (Export is different than Save in GIMP).

Once installed, you can open a .gbr or .gbm using the file -> open, or by dropping the file onto the gimp toolbox palette. For export just use the desired extension in the outgoing filename to select the export type  (.gbr for tileset, .gbm to generate tilemap and tileset).

It should not be necessary to make a folder for installing the plug-in, but I haven't used windows GIMP for a couple years so I can't say for sure.

**Comment by retroarch-girl** [comment]
I don't understand. GBDK requires a C and H file.
So what can I do with gbr or gbm???

**Comment by bbbbbr** [comment]
Those are image formats used by GBTD and GBMB, somewhat obsolete Game Boy graphics editors. They are sometimes still used, for example with the ZGB engine optionally. This plugin is not for export to GBDK directly.
https://github.com/gbdk-2020/GBTD_GBMB

If you would like to learn more about Game Boy development, I recommend following some tutorials:
https://laroldsjubilantjunkyard.com/tutorials/
https://gbdk-2020.github.io/gbdk-2020/docs/api/docs_getting_started.html

**Comment by retroarch-girl** [comment]
is there a plugin for gimp to export to GBDK or for any other free graphics program?

**Comment by bbbbbr** [comment]
The previously mentioned `png2asset` that is part of GBDK provides the capability of converting png images from any graphics program to data that can be used in GBDK. Please explore the samples in GBDK-2020 for how to do that.
